### ISSUE TITLE
[User feedback] Filter is not working for user roles filter

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#20]
## dhis2

Username: ignacio.foche

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://who-dev.essi.upc.edu:8081/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=emav3y

Filter is not working for user roles filter

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1537965584811286777.png )

**Comment by adrianq** [comment]
This has been fixed as part of the release https://github.com/EyeSeeTea/user-extended-app-blessed/releases/tag/v0.1.4
