### ISSUE TITLE
[User feedback] Filter filter by organisation

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#22]
## dhis2

Username: m.boniol

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=n77t9l

When selecting a region in the filter by organisation unit, and then selecting "Member states" level in the right selection, it does not only select member states for the region but all of them.
Also, the count of member states is 266 while I do not expect lot more than 193

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1538057029862624646.png )

**Comment by adrianq** [comment]
This has been fixed as part of the release https://github.com/EyeSeeTea/user-extended-app-blessed/releases/tag/v0.1.4. However, we are still using the 2.27 graphical component for OU assignment. If we upgrade to the latest 2.30 d2-ui library the component can provide a much better user experience. Something for the future...

The number of countries has to do with WHO OU tree and some internal concerns. Nothing to do with the app
