### ISSUE TITLE
[User feedback] Export button not responding

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#24]
## dhis2

Username: teena.kunjumen

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=e5lg4m

Failing to export a selection on 77 records (all NHWA data managers from Region and Member States)
Thanks for prioritising.
Regards, 
Teena

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1538990110371996007.png )

**Comment by adrianq** [comment]
We already have a spinner so closing this one
