### ISSUE TITLE
[User feedback] Could not remove an account

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#25]
## dhis2

Username: m.boniol

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=qqpvix

I tried to remove a demo country account that was created for Bahrain in the PROD platform.
It did not workers. Error message informed that action could not be done.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1541603094148572880.png )

**Comment by adrianq** [comment]
Already reported by email. This is a problem in the db not in the user extended app
