### ISSUE TITLE
[User feedback] Filter too slow

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#26]
## dhis2

Username: m.boniol

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=l73xvs

Hello,
I am trying to extract information on the subgroup of NWHA country team.
But the filter slows everything down. The blue bar is moving, but no outcome. 
(I have a perfect connection, on a sunday evening before the analytics running. So if this is slow, it would be impossible otherwise...)
Best regards,
Mathieu

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-156857709214561387.png )

**Comment by SferaDev** [comment]
Confirmed.

Created issues for follow-up:

- Redmine (feedback with the client): http://who-dev.essi.upc.edu:8083/issues/2482

- EyeSeeTea (development): https://github.com/EyeSeeTea/user-extended-app/issues/157
