### ISSUE TITLE
[User feedback] gfuty

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#35]
## dhis2

Username: hani2

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
- Platform: Win32

## User report
URL: https://sd.dhis2.site/trainingfmoh/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=l364m2

gserye

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1598695553904649602.png )

**Comment by adrianq** [comment]
Closing as it seems to be a fake issue
