### ISSUE TITLE
[User feedback] fff

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#37]
## dhis2

Username: rndoma

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://sandbox.bluesquare.org/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=uamaew

fff

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1600680370228585410.png )

**Comment by adrianq** [comment]
Closing this issue as it seems to be a dummy issue. Feel free to reopen it and drop a comment otherwise
