### ISSUE TITLE
[User feedback] Can not remove the app from DHIS2v235

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#40]
## dhis2

Username: admin

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
- Platform: Win32

## User report
URL: http://dreamsmis.rw/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=cb5cuj

Unfortunately, i did not verify the app version compartibility and installed it on version 2.35. after verification, the users were imported but i can not update them, yet i need to assign them to different org units. secondly, i cannot remove it from the stadard app menu. can you please guide me how i can achieve this? I am very stack. 
Thank you.
my email is amuramira@gmail.com
Absolom

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1609157350366197613.png )

**Comment by adrianq** [comment]
User-extended-app isn't supported for DHIS2 2.35. The latest version we support is DHIS2 2.34 and we have no plans to support 2.35 for now. Unfortunately, we cannot help with the first comment.

Regarding the second comment, we have been able to install and uninstall the app in a DHIS2 2.35 without any problem.

**Comment by adrianq** [comment]
This app is now supported for DHIS2 2.35. See https://github.com/EyeSeeTea/user-extended-app-blessed/releases/tag/v0.6.0
