### ISSUE TITLE
[User feedback] Paging error filtering by group

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#41]
## dhis2

Username: idelcano

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=6c3ic1

I was trying to delete a userGroup unassigning first all its users, and I have found some errors:

1. When listing all the users filtering by a group, all the existing ones do not appear (I have not tested the other filters, they may also fail).

2. 
There are users that are assigned looking in the api, but not shown in the app. For example, when "SS_GEN_AggData_Entry" only has 3 users assigned, it doesn't show them to me.

Tested with user extended app v0.4.0 (installed in prod), and with v0.3.0 (installed in my docker)

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1610647802275203923.png )

**Comment by idelcano** [comment]
I have checked with the rest of the filters and it also happens, not only with groups.

**Comment by adrianq** [comment]
This will be fixed in 0.6.0
