### ISSUE TITLE
[User feedback] count stops at 50. Paging?

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#43]
## dhis2

Username: ramon.pomareta

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=hnxryw

I've filtered by username, and the app says I've selected 50 users, but I know there are like 270 users matching this filter. When I export, it exports all expected users.

However, I cannot check what I am selecting since there's no paging. Is this a bug or a feature still not present in the app?

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1617806230161698532.png )

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/user-extended-app-blessed/releases/tag/v0.7.0
