### ISSUE TITLE
[User feedback] Error with OU capture

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#44]
## dhis2

Username: lise.grout

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=1frpg1

You can't change the OU capture when there is an error (you click on the name of the country and nothing happen, you are not redirected to the pop up where you can select the OU, as per the OU output behavior)

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1617960212267787317.png )

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/user-extended-app-blessed/releases/tag/v0.7.0
