### ISSUE TITLE
[User feedback] 50 users limit

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#45]
## dhis2

Username: marianne_henry@abtassoc.com

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
- Platform: Win32

## User report
URL: https://vectorlinkcollect.org/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=vcx61b

There should be more than 50 users when I select these two criteria (role and group). When I select the users from this list, and then delete the filter to individually search for additional users to add to the selected list, my originally selected users are not longer selected. 

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1619722050365748059.png )

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/user-extended-app-blessed/releases/tag/v0.7.0
