### ISSUE TITLE
[User feedback] OU Capture column not working

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#46]
## dhis2

Username: idelcano

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=gte3al

I get this error several times, the OU Capture column does not have the correct name, and if you press to add orgunits it does nothing.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1620638776723175960.png )

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/user-extended-app-blessed/releases/tag/v0.7.0
