### ISSUE TITLE
[User feedback] Data entry OU doesn't show the OU selector graphic component

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#47]
## dhis2

Username: ignacio.foche

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2-demo/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=n2gfeu

Data entry OU doesn't show the OU selector graphic component when replicating from table another user

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1620653997129162721.png )

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/user-extended-app-blessed/releases/tag/v0.7.0
