### ISSUE TITLE
[User feedback] Add more descriptive information in copy in user

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/user-extended-app-blessed#48]
## dhis2

Username: idelcano

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2/api/apps/User-Extended-App/index.html#/list/userSection/user?_k=jq67zo

When some user names are equals i can't know what is the desired user.

Maybe we could add the username:
Amir Aman (username)

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1621267983639181254.png )

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/user-extended-app-blessed/releases/tag/v0.7.0
